# Generated by Django 3.2.4 on 2021-08-29 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrar', '0002_alter_materiales_carrera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materiales',
            name='nombre',
            field=models.CharField(max_length=20, verbose_name='Nombre'),
        ),
    ]
