# Generated by Django 3.2.4 on 2021-08-29 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrar', '0003_alter_materiales_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('correo', models.EmailField(max_length=254, verbose_name='Correo')),
                ('telefono', models.CharField(max_length=10, verbose_name='Telefono')),
                ('area', models.CharField(max_length=25, verbose_name='Area')),
                ('cargo', models.CharField(max_length=30, verbose_name='Cargo')),
                ('turno', models.CharField(max_length=10)),
                ('imagen', models.ImageField(null=True, upload_to='fotos empleados', verbose_name='Fotografía')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'ordering': ['-created'],
            },
        ),
    ]
