# Generated by Django 3.2.4 on 2021-08-29 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrar', '0004_empleados'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleados',
            name='actividades',
            field=models.TextField(default=1, verbose_name='Actividades'),
            preserve_default=False,
        ),
    ]
