# Generated by Django 3.2.4 on 2021-08-29 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrar', '0005_empleados_actividades'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleados',
            name='nombre',
            field=models.CharField(max_length=30, verbose_name='Nombre Completo'),
        ),
    ]
