# Generated by Django 3.2.4 on 2021-08-29 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrar', '0007_alter_empleados_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='noticias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30, verbose_name='Nombre')),
                ('descripcion', models.TextField(verbose_name='Actividades')),
                ('imagen', models.ImageField(null=True, upload_to='fotosnoticias', verbose_name='Fotografia')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Noticia',
                'verbose_name_plural': 'Noticias',
                'ordering': ['-created'],
            },
        ),
        migrations.AlterField(
            model_name='materiales',
            name='carrera',
            field=models.CharField(max_length=50, verbose_name='Carrera'),
        ),
        migrations.AlterField(
            model_name='materiales',
            name='matricula',
            field=models.CharField(max_length=30, verbose_name='Matricula'),
        ),
        migrations.AlterField(
            model_name='materiales',
            name='nombre',
            field=models.CharField(max_length=50, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='materiales',
            name='practica',
            field=models.CharField(max_length=40, verbose_name='Nombre Practica'),
        ),
    ]
